repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
    #- id: terraform_tfsec
    - id: terraform_docs
    # Install the git hook scripts
    #pre-commit install