# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  mvcmovie:
    hostname: mvcmovie
    container_name: mvcmovie
    depends_on: 
      - database
    image: mvcmovie
    build:
      context: .
      dockerfile: MvcMovie/Dockerfile
    ports:
      - "5000:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Prod
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    networks: 
      - mvcmovie
  
  database:
    hostname: database
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes: 
      - ./data/database:/var/lib/postgresql/data
    networks: 
      - mvcmovie
      

networks: 
  mvcmovie:
    driver: bridge