---
###############################################################################
# redhat 8.0 require this
##############################################################################
- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: no
  vars_prompt:
  - name: "sshKey"
    prompt: "Enter ssh key file path: (ignore if local)"
    default: "suluq"
