# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  database:
    hostname: database
    container_name: database
    image: postgres
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes: 
      - "./data/database:/var/lib/postgresql/data"
    networks: 
      - todoapi
  todoapi:
    container_name: todoapi
    hostname: todoapi
    depends_on: 
      - database
    image: todoapi
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    ports:
      - "5001:80"
    volumes: 
      - "./data/web:/remote_debugger:rw"
    networks: 
      - todoapi
  
networks: 
  todoapi:
    driver: bridge