# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  pingapp:
    hostname: pingapp
    container_name: pingapp
    depends_on: 
      - db
    image: pingapp
    build:
      context: .
      dockerfile: pingapp/Dockerfile
    ports:
      - "5000:80"
    networks: 
      - pingapp
  
  db:
    hostname: db
    container_name: db
    image: postgres
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    networks: 
      - pingapp

networks: 
  pingapp:
    driver: bridge