# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  contosouniversity:
    image: contosouniversity
    depends_on: 
      - database
    build:
      context: .
      dockerfile: ContosoUniversity/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./debug/vsdbg:/remote_debugger:rw

  database:
    image: postgres
    hostname: database
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    restart: always
    
    volumes:
      - ./debug/db:/var/lib/postgresql/data