# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  database:
    image: postgres
    hostname: database
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    restart: always
    
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - contosouniversity
  
  contosouniversity:
    hostname: contosouniversity
    container_name: contosouniversity
    image: contosouniversity
    depends_on:
      - database
    build:
      context: .
      dockerfile: ContosoUniversity/Dockerfile
    ports:
      - "5000:80"

    environment: 
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    volumes:
      - ./data/web:/app
    networks: 
      - contosouniversity

networks:
  contosouniversity:
    driver: bridge 